import { Color } from "@/features/product/types";

export const COLORS: Color[] = [
  { name: "Black", hex: "#000000" },
  { name: "White", hex: "#FFFFFF" },
  { name: "Gray", hex: "#808080" },
  { name: "Silver", hex: "#C0C0C0" },
  { name: "Red", hex: "#FF0000" },
  { name: "Maroon", hex: "#800000" },
  { name: "Pink", hex: "#FFC0CB" },
  { name: "Rose", hex: "#FF007F" },
  { name: "Orange", hex: "#FFA500" },
  { name: "Coral", hex: "#FF7F50" },
  { name: "Yellow", hex: "#FFFF00" },
  { name: "Gold", hex: "#FFD700" },
  { name: "Green", hex: "#008000" },
  { name: "Lime", hex: "#00FF00" },
  { name: "Olive", hex: "#808000" },
  { name: "Teal", hex: "#008080" },
  { name: "Mint", hex: "#98FF98" },
  { name: "Blue", hex: "#0000FF" },
  { name: "Navy", hex: "#000080" },
  { name: "Sky Blue", hex: "#87CEEB" },
  { name: "Cyan", hex: "#00FFFF" },
  { name: "Purple", hex: "#800080" },
  { name: "Violet", hex: "#EE82EE" },
  { name: "Lavender", hex: "#E6E6FA" },
  { name: "Magenta", hex: "#FF00FF" },
  { name: "Brown", hex: "#A52A2A" },
  { name: "Beige", hex: "#F5F5DC" },
  { name: "Tan", hex: "#D2B48C" },
  { name: "Cream", hex: "#FFFDD0" },
  { name: "Burgundy", hex: "#800020" },
  { name: "Indigo", hex: "#4B0082" },
  { name: "Turquoise", hex: "#40E0D0" },
  { name: "Peach", hex: "#FFE5B4" },
  { name: "Khaki", hex: "#F0E68C" },
  { name: "Charcoal", hex: "#36454F" },
];

export const SIZES: string[] = [
  "XXS",
  "XS",
  "S",
  "M",
  "L",
  "XL",
  "XXL",
  "XXXL",
  "One Size",
];
export const AppRoutes = {
  HOME: "/",
  CART: "/cart",
  PRODUCTS: "/products",
  PRODUCT: "/products/:id",
  LOGIN: "/login",
  REGISTER: "/register",
  GOOGLE_AUTH_LOGIN: "/google-auth-login",
  GOOGLE_AUTH_REGISTER: "/google-auth-register",
  USER: "/user",
  USER_ORDERS: "/orders",
  SUPPORT: "/support",
  NOT_FOUND: "not_found",
} as const;
