import "@/app/globals.css";
import StoreProvider from "@/app/providers/StoreProvider";
import Toast from "@/components/feedback/Toast";
import { NotificationProvider } from "@/features/notifications";
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";

const roboto = localFont({
  src: "./fonts/Roboto.ttf",
  variable: "--font-roboto",
  weight: "100 900",
});

const spaceGrotesk = localFont({
  src: "./fonts/SpaceGrotesk.ttf",
  variable: "--font-space-grotesk",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "FakeLando - Your Ultimate Online Store for Electronics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} ${spaceGrotesk.className} antialiased`}
      >
        <StoreProvider>
          <NotificationProvider>
            {/* <TopLoadingBar /> */}
            {children}
            <Toast />
          </NotificationProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
